/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam_student;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author XII Info
 */
public class Mainframe_Student extends javax.swing.JFrame {

    /**
     * Creates new form MainframeStudent
     */
    String clas,questionPaperId,name,selectedQuestionPaperId,correctPassword,enteredPassword,subject;
    int studentId, rollNo;
    DB_Connection d = new DB_Connection();
    Connection con;
    ResultSet rs, rs2, rs3;
    PreparedStatement ps;

    public Mainframe_Student(String clas, int studentId) throws SQLException, SQLException {
        initComponents();
        this.clas = clas;
        this.studentId = studentId;
        con = d.DB_Connection();
    }

    Mainframe_Student(String QuestionPaperID, int StudeId, String Clas) throws SQLException {
        initComponents();
        clas = Clas;
        studentId = StudeId;
        con = d.DB_Connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        WriteXam_BTN = new javax.swing.JButton();
        QuestionPaperID_CB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Back_BTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ClassTF = new javax.swing.JTextField();
        ClassLBL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        RollLBL = new javax.swing.JLabel();
        RollTF = new javax.swing.JTextField();
        NameLBL = new javax.swing.JLabel();
        StudentIdTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel6.setText("jLabel6");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        WriteXam_BTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WriteXam_BTN.setText("Write Exam");
        WriteXam_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteXam_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(WriteXam_BTN);
        WriteXam_BTN.setBounds(308, 242, 105, 25);

        QuestionPaperID_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QuestionPaperID" }));
        QuestionPaperID_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionPaperID_CBActionPerformed(evt);
            }
        });
        getContentPane().add(QuestionPaperID_CB);
        QuestionPaperID_CB.setBounds(278, 128, 161, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Your Question Paper ID here..");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 93, 183, 17);

        Back_BTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Back_BTN.setText("Back ");
        Back_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Back_BTN);
        Back_BTN.setBounds(460, 20, 65, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Home");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 0, 62, 43);

        ClassTF.setEditable(false);
        getContentPane().add(ClassTF);
        ClassTF.setBounds(90, 260, 108, 29);

        ClassLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClassLBL.setText("Class:");
        getContentPane().add(ClassLBL);
        ClassLBL.setBounds(40, 260, 47, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Name:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 47, 24);

        NameTF.setEditable(false);
        getContentPane().add(NameTF);
        NameTF.setBounds(90, 210, 108, 29);

        RollLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RollLBL.setText("Roll No:");
        getContentPane().add(RollLBL);
        RollLBL.setBounds(40, 160, 67, 29);

        RollTF.setEditable(false);
        RollTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollTFActionPerformed(evt);
            }
        });
        getContentPane().add(RollTF);
        RollTF.setBounds(90, 160, 108, 29);

        NameLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLBL.setText("ID:");
        getContentPane().add(NameLBL);
        NameLBL.setBounds(70, 120, 67, 26);

        StudentIdTF.setEditable(false);
        getContentPane().add(StudentIdTF);
        StudentIdTF.setBounds(90, 110, 111, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\XII Info\\Desktop\\dsadsadsad.PNG")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 550, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QuestionPaperID_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionPaperID_CBActionPerformed
        if (QuestionPaperID_CB.getSelectedIndex() > 0) {
            try {
                int noOfQuestionsInQB = 0, noOfQuestionsInQP = 0;

                //no of qns in qbank
                selectedQuestionPaperId = (String) QuestionPaperID_CB.getSelectedItem();
                ps = con.prepareStatement("select noofquestions,subject from questionpaperdetails where questionpaperid=?");
                ps.setString(1, selectedQuestionPaperId);
                rs3 = ps.executeQuery();
                if (rs3.next()) {
                    noOfQuestionsInQB = rs3.getInt("noofquestions");
                    subject = rs3.getString("Subject");
                }

                //no of qns in qpaper
                ps = con.prepareStatement("select count(questionID) from questionpaper where questionpaperid=?");
                ps.setString(1, selectedQuestionPaperId);
                rs3 = ps.executeQuery();
                if (rs3.next()) {
                    noOfQuestionsInQP = rs3.getInt("count(questionID)");
                }

                if (noOfQuestionsInQP < noOfQuestionsInQB) {
                    JOptionPane.showMessageDialog(this, "Sorry..QuestionPaper is not yet ready!!!!");
                    Student_Login s = new Student_Login(clas, studentId);
                    this.setVisible(false);
                    s.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Mainframe_Student.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }
    }//GEN-LAST:event_QuestionPaperID_CBActionPerformed

    private void WriteXam_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteXam_BTNActionPerformed
        try {
            //getting password form database
            ps = con.prepareStatement("select password from questionpaperdetails where questionpaperid=?");
            ps.setString(1, selectedQuestionPaperId);
            rs2 = ps.executeQuery();
            if (rs2.next()) {
                correctPassword = rs2.getString("password");
            }

            //taking password from student and checking
            enteredPassword = null;
            enteredPassword = (String) JOptionPane.showInputDialog(enteredPassword);
            if (enteredPassword.equals(correctPassword)) {
                WriteExam r = new WriteExam(selectedQuestionPaperId, studentId, clas, subject,name,rollNo);
                this.dispose();
                r.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Password entered!!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mainframe_Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WriteXam_BTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        QuestionPaperID_CB.requestFocus();
        try {
            ps = con.prepareStatement("Select QuestionPaperId from questionpaperdetails where class=?");
            ps.setString(1, clas);
            rs = ps.executeQuery();
            while (rs.next()) {
                questionPaperId = rs.getString("QuestionpaperId");
                QuestionPaperID_CB.addItem(questionPaperId);
            }
            ps = con.prepareStatement("select * from stu_details where StudentId=? and class=?");
            ps.setString(1, studentId + "");
            ps.setString(2, clas);
            rs = ps.executeQuery();
            while (rs.next()) {
                name = rs.getString("name");
                rollNo = rs.getInt("RollNo");
            }
            StudentIdTF.setText(Integer.toString(studentId));
            RollTF.setText(Integer.toString(rollNo));
            ClassTF.setText(clas);
            NameTF.setText(name);
        } catch (SQLException ex) {
            Logger.getLogger(Mainframe_Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void Back_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BTNActionPerformed
        try {
            Student_Login s = new Student_Login(clas, studentId);
            this.setVisible(false);
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Mainframe_Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Back_BTNActionPerformed

    private void RollTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_BTN;
    private javax.swing.JLabel ClassLBL;
    private javax.swing.JTextField ClassTF;
    private javax.swing.JLabel NameLBL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JComboBox QuestionPaperID_CB;
    private javax.swing.JLabel RollLBL;
    private javax.swing.JTextField RollTF;
    private javax.swing.JTextField StudentIdTF;
    private javax.swing.JButton WriteXam_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
