/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam_student;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author XII Info
 */
public class Student_Login extends javax.swing.JFrame {

    int studentId;
    String clas, password2 = null, password1;

    DB_Connection d = new DB_Connection();
    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form Student_Login
     */
    public Student_Login() throws SQLException {
        initComponents();
        con = d.DB_Connection();
        id_TF.requestFocus();
    }

    Student_Login(String clas, int StudentId) throws SQLException {
        initComponents();
        con = d.DB_Connection();
        id_TF.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_LBL = new javax.swing.JLabel();
        titleUserID_LBL = new javax.swing.JLabel();
        titlePassword_LBL = new javax.swing.JLabel();
        Login_BTN = new javax.swing.JButton();
        id_TF = new javax.swing.JTextField();
        password_PF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_LBL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title_LBL.setText("Student Login");

        titleUserID_LBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleUserID_LBL.setText("UserId:");

        titlePassword_LBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titlePassword_LBL.setText("Password:");

        Login_BTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Login_BTN.setText("Login");
        Login_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BTNActionPerformed(evt);
            }
        });

        id_TF.setBorder(null);

        password_PF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_PFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Login_BTN)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title_LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleUserID_LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlePassword_LBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password_PF)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleUserID_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePassword_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_PF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Login_BTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BTNActionPerformed

        if (id_TF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Don't Leave Any Fields Empty!!");
        } else {
            try {
                studentId = Integer.parseInt(id_TF.getText());
                password1 = new String(password_PF.getPassword());
                ps = con.prepareStatement("Select * from stu_details where studentId=?");
                ps.setInt(1, studentId);
                rs = ps.executeQuery();
                if (rs.next()) {
                    password2 = rs.getString("password");
                    clas = rs.getString("class");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Id!!!!! Try Again");
                    return;
                }
                if (password2.equals(password1)) {
                    Mainframe_Student br = new Mainframe_Student(clas, studentId);
                    br.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Password!!!!! Try Again");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Student_Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Login_BTNActionPerformed

    private void password_PFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_PFActionPerformed
        Login_BTN.doClick();
    }//GEN-LAST:event_password_PFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Student_Login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Student_Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_BTN;
    private javax.swing.JTextField id_TF;
    private javax.swing.JPasswordField password_PF;
    private javax.swing.JLabel titlePassword_LBL;
    private javax.swing.JLabel titleUserID_LBL;
    private javax.swing.JLabel title_LBL;
    // End of variables declaration//GEN-END:variables
}
