/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author XII Info
 */
public class DeleteQuestionPaper extends javax.swing.JFrame {

    DBConnection d = new DBConnection();
    Connection con;
    String questionPaperId, teacherID,name;
    PreparedStatement ps, ps2;

    public DeleteQuestionPaper(String teacherID,String name) {
        try {
            initComponents();
            this.teacherID = teacherID;
            this.name = name;
            con = d.DB_Connection();
            ResultSet rs;
            ps2 = con.prepareStatement("Select distinct QuestionPaperId from questionpaper natural join questionpaperdetails where TeacherID=?");
            ps2.setString(1, teacherID);
            rs = ps2.executeQuery();
            questionPaperId_CB.addItem("questionPaperId");
            while (rs.next()) {
                questionPaperId = rs.getString("QuestionpaperId");
                questionPaperId_CB.addItem(questionPaperId);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeleteQuestionPaper.class.getName()).log(Level.SEVERE, null, ex);
        }
    questionPaperId_CB.requestFocus();
    }

    public DeleteQuestionPaper() {
        try {
            initComponents();
            con = d.DB_Connection();
            ResultSet rs2;
            ps2 = con.prepareStatement("Select distinct QuestionPaperId from questionpaper");
            rs2 = ps2.executeQuery();
            questionPaperId_CB.addItem("questionPaperId");
            while (rs2.next()) {
                questionPaperId = rs2.getString("QuestionpaperId");
                questionPaperId_CB.addItem(questionPaperId);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeleteQuestionPaper.class.getName()).log(Level.SEVERE, null, ex);
        }
    questionPaperId_CB.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionPaperIdLBL = new javax.swing.JLabel();
        questionPaperId_CB = new javax.swing.JComboBox();
        deleteQuestionPaper_BTN = new javax.swing.JButton();
        back_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        QuestionPaperIdLBL.setText("Q.Paper.ID");

        questionPaperId_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionPaperId_CBActionPerformed(evt);
            }
        });

        deleteQuestionPaper_BTN.setText("Delete QuestionPaper");
        deleteQuestionPaper_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteQuestionPaper_BTNActionPerformed(evt);
            }
        });

        back_BTN.setText("Back");
        back_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_BTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Delete Question Paper");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(QuestionPaperIdLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionPaperId_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(back_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteQuestionPaper_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteQuestionPaper_BTN, questionPaperId_CB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(back_BTN)
                        .addComponent(jLabel1)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuestionPaperIdLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionPaperId_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(deleteQuestionPaper_BTN)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void questionPaperId_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionPaperId_CBActionPerformed
        questionPaperId = (String) questionPaperId_CB.getSelectedItem();
        //deleteQuestionPaper_BTN.doClick();
    }//GEN-LAST:event_questionPaperId_CBActionPerformed

    private void deleteQuestionPaper_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteQuestionPaper_BTNActionPerformed

        try {
            if (questionPaperId_CB.getSelectedIndex() > 0) {
                int rowsuccess;
                ps = con.prepareStatement("Delete from Questionpaperdetails where questionpaperid=?");
                ps.setString(1, questionPaperId);
                rowsuccess = ps.executeUpdate();

                ps = con.prepareStatement("delete from questionpaper  where questionPaperId=?");
                ps.setString(1, (String) questionPaperId_CB.getSelectedItem());
                int j = ps.executeUpdate();

                if ((rowsuccess == 1) && (j == 1)) {
                    JOptionPane.showMessageDialog(this, "Deleted questionPaperId successfully!!!");
                 questionPaperId_CB.removeItem(questionPaperId);
                }
               
            } else {
                //JOptionPane.showMessageDialog(this, "Select a chapter to delete!!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeleteQuestionPaper.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deleteQuestionPaper_BTNActionPerformed

    private void back_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_BTNActionPerformed
        try {
            Home m = new Home(teacherID);
            this.setVisible(false);
            m.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CreateQuestionPaper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_back_BTNActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            con.close();
            ps.close();
            ps2.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditChapters.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nameLBL.setText(name);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteQuestionPaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QuestionPaperIdLBL;
    private javax.swing.JButton back_BTN;
    private javax.swing.JButton deleteQuestionPaper_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JComboBox questionPaperId_CB;
    // End of variables declaration//GEN-END:variables
}
